/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.database.tables;


import cn.hlvan.database.Indexes;
import cn.hlvan.database.Keys;
import cn.hlvan.database.Super;
import cn.hlvan.database.tables.records.BrandClassifyRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BrandClassify extends TableImpl<BrandClassifyRecord> {

    private static final long serialVersionUID = 598829568;

    /**
     * The reference instance of <code>super.brand_classify</code>
     */
    public static final BrandClassify BRAND_CLASSIFY = new BrandClassify();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BrandClassifyRecord> getRecordType() {
        return BrandClassifyRecord.class;
    }

    /**
     * The column <code>super.brand_classify.id</code>. 商标与类别
     */
    public final TableField<BrandClassifyRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "商标与类别");

    /**
     * The column <code>super.brand_classify.brand_id</code>. 品牌id
     */
    public final TableField<BrandClassifyRecord, Integer> BRAND_ID = createField("brand_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "品牌id");

    /**
     * The column <code>super.brand_classify.classify</code>. 类别id
     */
    public final TableField<BrandClassifyRecord, Integer> CLASSIFY = createField("classify", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "类别id");

    /**
     * The column <code>super.brand_classify.created_at</code>.
     */
    public final TableField<BrandClassifyRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>super.brand_classify</code> table reference
     */
    public BrandClassify() {
        this(DSL.name("brand_classify"), null);
    }

    /**
     * Create an aliased <code>super.brand_classify</code> table reference
     */
    public BrandClassify(String alias) {
        this(DSL.name(alias), BRAND_CLASSIFY);
    }

    /**
     * Create an aliased <code>super.brand_classify</code> table reference
     */
    public BrandClassify(Name alias) {
        this(alias, BRAND_CLASSIFY);
    }

    private BrandClassify(Name alias, Table<BrandClassifyRecord> aliased) {
        this(alias, aliased, null);
    }

    private BrandClassify(Name alias, Table<BrandClassifyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Super.SUPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BRAND_CLASSIFY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BrandClassifyRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BRAND_CLASSIFY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BrandClassifyRecord> getPrimaryKey() {
        return Keys.KEY_BRAND_CLASSIFY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BrandClassifyRecord>> getKeys() {
        return Arrays.<UniqueKey<BrandClassifyRecord>>asList(Keys.KEY_BRAND_CLASSIFY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrandClassify as(String alias) {
        return new BrandClassify(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrandClassify as(Name alias) {
        return new BrandClassify(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BrandClassify rename(String name) {
        return new BrandClassify(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BrandClassify rename(Name name) {
        return new BrandClassify(name, null);
    }
}
