/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.database.tables;


import cn.hlvan.database.Indexes;
import cn.hlvan.database.Keys;
import cn.hlvan.database.Super;
import cn.hlvan.database.tables.records.CommodityClassifyRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommodityClassify extends TableImpl<CommodityClassifyRecord> {

    private static final long serialVersionUID = 1455229615;

    /**
     * The reference instance of <code>super.commodity_classify</code>
     */
    public static final CommodityClassify COMMODITY_CLASSIFY = new CommodityClassify();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CommodityClassifyRecord> getRecordType() {
        return CommodityClassifyRecord.class;
    }

    /**
     * The column <code>super.commodity_classify.id</code>. 商品分类
     */
    public final TableField<CommodityClassifyRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "商品分类");

    /**
     * The column <code>super.commodity_classify.name</code>. 分类名称
     */
    public final TableField<CommodityClassifyRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "分类名称");

    /**
     * The column <code>super.commodity_classify.cid</code>. 父分类id
     */
    public final TableField<CommodityClassifyRecord, Integer> CID = createField("cid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "父分类id");

    /**
     * The column <code>super.commodity_classify.created_at</code>.
     */
    public final TableField<CommodityClassifyRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>super.commodity_classify.updated_at</code>.
     */
    public final TableField<CommodityClassifyRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>super.commodity_classify</code> table reference
     */
    public CommodityClassify() {
        this(DSL.name("commodity_classify"), null);
    }

    /**
     * Create an aliased <code>super.commodity_classify</code> table reference
     */
    public CommodityClassify(String alias) {
        this(DSL.name(alias), COMMODITY_CLASSIFY);
    }

    /**
     * Create an aliased <code>super.commodity_classify</code> table reference
     */
    public CommodityClassify(Name alias) {
        this(alias, COMMODITY_CLASSIFY);
    }

    private CommodityClassify(Name alias, Table<CommodityClassifyRecord> aliased) {
        this(alias, aliased, null);
    }

    private CommodityClassify(Name alias, Table<CommodityClassifyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Super.SUPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COMMODITY_CLASSIFY_PRIMARY, Indexes.COMMODITY_CLASSIFY_UK_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CommodityClassifyRecord, Integer> getIdentity() {
        return Keys.IDENTITY_COMMODITY_CLASSIFY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CommodityClassifyRecord> getPrimaryKey() {
        return Keys.KEY_COMMODITY_CLASSIFY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CommodityClassifyRecord>> getKeys() {
        return Arrays.<UniqueKey<CommodityClassifyRecord>>asList(Keys.KEY_COMMODITY_CLASSIFY_PRIMARY, Keys.KEY_COMMODITY_CLASSIFY_UK_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityClassify as(String alias) {
        return new CommodityClassify(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityClassify as(Name alias) {
        return new CommodityClassify(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CommodityClassify rename(String name) {
        return new CommodityClassify(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CommodityClassify rename(Name name) {
        return new CommodityClassify(name, null);
    }
}
