/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.database.tables;


import cn.hlvan.database.Indexes;
import cn.hlvan.database.Keys;
import cn.hlvan.database.Super;
import cn.hlvan.database.tables.records.PermissionRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Permission extends TableImpl<PermissionRecord> {

    private static final long serialVersionUID = -88008508;

    /**
     * The reference instance of <code>super.permission</code>
     */
    public static final Permission PERMISSION = new Permission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PermissionRecord> getRecordType() {
        return PermissionRecord.class;
    }

    /**
     * The column <code>super.permission.id</code>. 权限id
     */
    public final TableField<PermissionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "权限id");

    /**
     * The column <code>super.permission.code</code>. 权限码
     */
    public final TableField<PermissionRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "权限码");

    /**
     * The column <code>super.permission.name</code>. 权限名
     */
    public final TableField<PermissionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(50), this, "权限名");

    /**
     * The column <code>super.permission.description</code>. 权限描述
     */
    public final TableField<PermissionRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR(100), this, "权限描述");

    /**
     * The column <code>super.permission.system_id</code>. 系统id
     */
    public final TableField<PermissionRecord, Integer> SYSTEM_ID = createField("system_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "系统id");

    /**
     * The column <code>super.permission.created_at</code>.
     */
    public final TableField<PermissionRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>super.permission.updated_at</code>.
     */
    public final TableField<PermissionRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>super.permission</code> table reference
     */
    public Permission() {
        this(DSL.name("permission"), null);
    }

    /**
     * Create an aliased <code>super.permission</code> table reference
     */
    public Permission(String alias) {
        this(DSL.name(alias), PERMISSION);
    }

    /**
     * Create an aliased <code>super.permission</code> table reference
     */
    public Permission(Name alias) {
        this(alias, PERMISSION);
    }

    private Permission(Name alias, Table<PermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Permission(Name alias, Table<PermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Super.SUPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PERMISSION_PRIMARY, Indexes.PERMISSION_UK_CODE_SYSTEM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PermissionRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PERMISSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PermissionRecord> getPrimaryKey() {
        return Keys.KEY_PERMISSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PermissionRecord>> getKeys() {
        return Arrays.<UniqueKey<PermissionRecord>>asList(Keys.KEY_PERMISSION_PRIMARY, Keys.KEY_PERMISSION_UK_CODE_SYSTEM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Permission as(String alias) {
        return new Permission(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Permission as(Name alias) {
        return new Permission(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Permission rename(String name) {
        return new Permission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Permission rename(Name name) {
        return new Permission(name, null);
    }
}
