/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.database.tables.records;


import cn.hlvan.database.tables.CommodityClassify;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommodityClassifyRecord extends UpdatableRecordImpl<CommodityClassifyRecord> implements Record5<Integer, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -357591615;

    /**
     * Setter for <code>super.commodity_classify.id</code>. 商品分类
     */
    public CommodityClassifyRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_classify.id</code>. 商品分类
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>super.commodity_classify.name</code>. 分类名称
     */
    public CommodityClassifyRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_classify.name</code>. 分类名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>super.commodity_classify.cid</code>. 父分类id
     */
    public CommodityClassifyRecord setCid(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_classify.cid</code>. 父分类id
     */
    public Integer getCid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>super.commodity_classify.created_at</code>.
     */
    public CommodityClassifyRecord setCreatedAt(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_classify.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>super.commodity_classify.updated_at</code>.
     */
    public CommodityClassifyRecord setUpdatedAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_classify.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CommodityClassify.COMMODITY_CLASSIFY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CommodityClassify.COMMODITY_CLASSIFY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CommodityClassify.COMMODITY_CLASSIFY.CID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return CommodityClassify.COMMODITY_CLASSIFY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return CommodityClassify.COMMODITY_CLASSIFY.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityClassifyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityClassifyRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityClassifyRecord value3(Integer value) {
        setCid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityClassifyRecord value4(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityClassifyRecord value5(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityClassifyRecord values(Integer value1, String value2, Integer value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommodityClassifyRecord
     */
    public CommodityClassifyRecord() {
        super(CommodityClassify.COMMODITY_CLASSIFY);
    }

    /**
     * Create a detached, initialised CommodityClassifyRecord
     */
    public CommodityClassifyRecord(Integer id, String name, Integer cid, Timestamp createdAt, Timestamp updatedAt) {
        super(CommodityClassify.COMMODITY_CLASSIFY);

        set(0, id);
        set(1, name);
        set(2, cid);
        set(3, createdAt);
        set(4, updatedAt);
    }
}
