/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.database.tables.records;


import cn.hlvan.database.tables.Commodity;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommodityRecord extends UpdatableRecordImpl<CommodityRecord> implements Record11<Integer, String, Integer, String, Boolean, String, Timestamp, Timestamp, Integer, Integer, String> {

    private static final long serialVersionUID = 1087793147;

    /**
     * Setter for <code>super.commodity.id</code>. 商品id
     */
    public CommodityRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity.id</code>. 商品id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>super.commodity.name</code>. 商品名称
     */
    public CommodityRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity.name</code>. 商品名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>super.commodity.commodity_classify_id</code>. 分类id
     */
    public CommodityRecord setCommodityClassifyId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity.commodity_classify_id</code>. 分类id
     */
    public Integer getCommodityClassifyId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>super.commodity.describe</code>. 商品简介
     */
    public CommodityRecord setDescribe(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity.describe</code>. 商品简介
     */
    public String getDescribe() {
        return (String) get(3);
    }

    /**
     * Setter for <code>super.commodity.enabled</code>. 0-上架，1-下架
     */
    public CommodityRecord setEnabled(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity.enabled</code>. 0-上架，1-下架
     */
    public Boolean getEnabled() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>super.commodity.picture</code>. 商品图片
     */
    public CommodityRecord setPicture(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity.picture</code>. 商品图片
     */
    public String getPicture() {
        return (String) get(5);
    }

    /**
     * Setter for <code>super.commodity.created_at</code>.
     */
    public CommodityRecord setCreatedAt(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>super.commodity.updated_at</code>.
     */
    public CommodityRecord setUpdatedAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>super.commodity.merchant_id</code>. 供应商id
     */
    public CommodityRecord setMerchantId(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity.merchant_id</code>. 供应商id
     */
    public Integer getMerchantId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>super.commodity.sale_total</code>. 销售量
     */
    public CommodityRecord setSaleTotal(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity.sale_total</code>. 销售量
     */
    public Integer getSaleTotal() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>super.commodity.details</code>. 商品详情
     */
    public CommodityRecord setDetails(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity.details</code>. 商品详情
     */
    public String getDetails() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, Integer, String, Boolean, String, Timestamp, Timestamp, Integer, Integer, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, Integer, String, Boolean, String, Timestamp, Timestamp, Integer, Integer, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Commodity.COMMODITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Commodity.COMMODITY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Commodity.COMMODITY.COMMODITY_CLASSIFY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Commodity.COMMODITY.DESCRIBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Commodity.COMMODITY.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Commodity.COMMODITY.PICTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Commodity.COMMODITY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Commodity.COMMODITY.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Commodity.COMMODITY.MERCHANT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Commodity.COMMODITY.SALE_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Commodity.COMMODITY.DETAILS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCommodityClassifyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getMerchantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getSaleTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getDetails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCommodityClassifyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getMerchantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getSaleTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDetails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value3(Integer value) {
        setCommodityClassifyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value4(String value) {
        setDescribe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value5(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value6(String value) {
        setPicture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value7(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value8(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value9(Integer value) {
        setMerchantId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value10(Integer value) {
        setSaleTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value11(String value) {
        setDetails(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord values(Integer value1, String value2, Integer value3, String value4, Boolean value5, String value6, Timestamp value7, Timestamp value8, Integer value9, Integer value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommodityRecord
     */
    public CommodityRecord() {
        super(Commodity.COMMODITY);
    }

    /**
     * Create a detached, initialised CommodityRecord
     */
    public CommodityRecord(Integer id, String name, Integer commodityClassifyId, String describe, Boolean enabled, String picture, Timestamp createdAt, Timestamp updatedAt, Integer merchantId, Integer saleTotal, String details) {
        super(Commodity.COMMODITY);

        set(0, id);
        set(1, name);
        set(2, commodityClassifyId);
        set(3, describe);
        set(4, enabled);
        set(5, picture);
        set(6, createdAt);
        set(7, updatedAt);
        set(8, merchantId);
        set(9, saleTotal);
        set(10, details);
    }
}
