/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.database.tables.records;


import cn.hlvan.database.tables.CommodityStock;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommodityStockRecord extends UpdatableRecordImpl<CommodityStockRecord> implements Record11<Integer, Boolean, String, Timestamp, Timestamp, BigDecimal, Timestamp, String, Integer, BigDecimal, Integer> {

    private static final long serialVersionUID = -783508402;

    /**
     * Setter for <code>super.commodity_stock.id</code>. 商品库存
     */
    public CommodityStockRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_stock.id</code>. 商品库存
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>super.commodity_stock.enabled</code>. 0-上架，1-下架
     */
    public CommodityStockRecord setEnabled(Boolean value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_stock.enabled</code>. 0-上架，1-下架
     */
    public Boolean getEnabled() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>super.commodity_stock.picture</code>. 商品图片
     */
    public CommodityStockRecord setPicture(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_stock.picture</code>. 商品图片
     */
    public String getPicture() {
        return (String) get(2);
    }

    /**
     * Setter for <code>super.commodity_stock.created_at</code>.
     */
    public CommodityStockRecord setCreatedAt(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_stock.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>super.commodity_stock.updated_at</code>.
     */
    public CommodityStockRecord setUpdatedAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_stock.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>super.commodity_stock.price</code>. 商品价格
     */
    public CommodityStockRecord setPrice(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_stock.price</code>. 商品价格
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>super.commodity_stock.pass_time</code>. 过期时间
     */
    public CommodityStockRecord setPassTime(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_stock.pass_time</code>. 过期时间
     */
    public Timestamp getPassTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>super.commodity_stock.attribute</code>. 规格
     */
    public CommodityStockRecord setAttribute(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_stock.attribute</code>. 规格
     */
    public String getAttribute() {
        return (String) get(7);
    }

    /**
     * Setter for <code>super.commodity_stock.commodity_id</code>. 商品id
     */
    public CommodityStockRecord setCommodityId(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_stock.commodity_id</code>. 商品id
     */
    public Integer getCommodityId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>super.commodity_stock.discount_price</code>. 优惠价
     */
    public CommodityStockRecord setDiscountPrice(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_stock.discount_price</code>. 优惠价
     */
    public BigDecimal getDiscountPrice() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>super.commodity_stock.total</code>. 库存
     */
    public CommodityStockRecord setTotal(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>super.commodity_stock.total</code>. 库存
     */
    public Integer getTotal() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Boolean, String, Timestamp, Timestamp, BigDecimal, Timestamp, String, Integer, BigDecimal, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Boolean, String, Timestamp, Timestamp, BigDecimal, Timestamp, String, Integer, BigDecimal, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CommodityStock.COMMODITY_STOCK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field2() {
        return CommodityStock.COMMODITY_STOCK.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CommodityStock.COMMODITY_STOCK.PICTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return CommodityStock.COMMODITY_STOCK.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return CommodityStock.COMMODITY_STOCK.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return CommodityStock.COMMODITY_STOCK.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return CommodityStock.COMMODITY_STOCK.PASS_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return CommodityStock.COMMODITY_STOCK.ATTRIBUTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return CommodityStock.COMMODITY_STOCK.COMMODITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return CommodityStock.COMMODITY_STOCK.DISCOUNT_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return CommodityStock.COMMODITY_STOCK.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component2() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getPassTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getAttribute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getCommodityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getDiscountPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value2() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getPassTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAttribute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getCommodityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getDiscountPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityStockRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityStockRecord value2(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityStockRecord value3(String value) {
        setPicture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityStockRecord value4(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityStockRecord value5(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityStockRecord value6(BigDecimal value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityStockRecord value7(Timestamp value) {
        setPassTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityStockRecord value8(String value) {
        setAttribute(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityStockRecord value9(Integer value) {
        setCommodityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityStockRecord value10(BigDecimal value) {
        setDiscountPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityStockRecord value11(Integer value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityStockRecord values(Integer value1, Boolean value2, String value3, Timestamp value4, Timestamp value5, BigDecimal value6, Timestamp value7, String value8, Integer value9, BigDecimal value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommodityStockRecord
     */
    public CommodityStockRecord() {
        super(CommodityStock.COMMODITY_STOCK);
    }

    /**
     * Create a detached, initialised CommodityStockRecord
     */
    public CommodityStockRecord(Integer id, Boolean enabled, String picture, Timestamp createdAt, Timestamp updatedAt, BigDecimal price, Timestamp passTime, String attribute, Integer commodityId, BigDecimal discountPrice, Integer total) {
        super(CommodityStock.COMMODITY_STOCK);

        set(0, id);
        set(1, enabled);
        set(2, picture);
        set(3, createdAt);
        set(4, updatedAt);
        set(5, price);
        set(6, passTime);
        set(7, attribute);
        set(8, commodityId);
        set(9, discountPrice);
        set(10, total);
    }
}
