/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.database.tables.records;


import cn.hlvan.database.tables.GoodsClassify;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsClassifyRecord extends UpdatableRecordImpl<GoodsClassifyRecord> implements Record6<Integer, String, Integer, Timestamp, Timestamp, Boolean> {

    private static final long serialVersionUID = 1170950280;

    /**
     * Setter for <code>super.goods_classify.id</code>. 商品分类
     */
    public GoodsClassifyRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>super.goods_classify.id</code>. 商品分类
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>super.goods_classify.name</code>. 分类名称
     */
    public GoodsClassifyRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>super.goods_classify.name</code>. 分类名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>super.goods_classify.p_id</code>. 父分类id
     */
    public GoodsClassifyRecord setPId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>super.goods_classify.p_id</code>. 父分类id
     */
    public Integer getPId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>super.goods_classify.created_at</code>.
     */
    public GoodsClassifyRecord setCreatedAt(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>super.goods_classify.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>super.goods_classify.updated_at</code>.
     */
    public GoodsClassifyRecord setUpdatedAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>super.goods_classify.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>super.goods_classify.enabled</code>. 是否可用
     */
    public GoodsClassifyRecord setEnabled(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>super.goods_classify.enabled</code>. 是否可用
     */
    public Boolean getEnabled() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Timestamp, Timestamp, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Timestamp, Timestamp, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GoodsClassify.GOODS_CLASSIFY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GoodsClassify.GOODS_CLASSIFY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return GoodsClassify.GOODS_CLASSIFY.P_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return GoodsClassify.GOODS_CLASSIFY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return GoodsClassify.GOODS_CLASSIFY.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return GoodsClassify.GOODS_CLASSIFY.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsClassifyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsClassifyRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsClassifyRecord value3(Integer value) {
        setPId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsClassifyRecord value4(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsClassifyRecord value5(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsClassifyRecord value6(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsClassifyRecord values(Integer value1, String value2, Integer value3, Timestamp value4, Timestamp value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GoodsClassifyRecord
     */
    public GoodsClassifyRecord() {
        super(GoodsClassify.GOODS_CLASSIFY);
    }

    /**
     * Create a detached, initialised GoodsClassifyRecord
     */
    public GoodsClassifyRecord(Integer id, String name, Integer pId, Timestamp createdAt, Timestamp updatedAt, Boolean enabled) {
        super(GoodsClassify.GOODS_CLASSIFY);

        set(0, id);
        set(1, name);
        set(2, pId);
        set(3, createdAt);
        set(4, updatedAt);
        set(5, enabled);
    }
}
