/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.database.tables.records;


import cn.hlvan.database.tables.Goods;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsRecord extends UpdatableRecordImpl<GoodsRecord> implements Record15<Integer, String, Integer, String, Boolean, String, Timestamp, Timestamp, Integer, Integer, String, Byte, BigDecimal, String, Double> {

    private static final long serialVersionUID = 260828572;

    /**
     * Setter for <code>super.goods.id</code>. 商品id
     */
    public GoodsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.id</code>. 商品id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>super.goods.name</code>. 商品名称
     */
    public GoodsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.name</code>. 商品名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>super.goods.commodity_classify_id</code>. 分类id
     */
    public GoodsRecord setCommodityClassifyId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.commodity_classify_id</code>. 分类id
     */
    public Integer getCommodityClassifyId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>super.goods.describe</code>. 商品简介
     */
    public GoodsRecord setDescribe(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.describe</code>. 商品简介
     */
    public String getDescribe() {
        return (String) get(3);
    }

    /**
     * Setter for <code>super.goods.enabled</code>. 0-上架，1-下架
     */
    public GoodsRecord setEnabled(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.enabled</code>. 0-上架，1-下架
     */
    public Boolean getEnabled() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>super.goods.picture</code>. 商品图片
     */
    public GoodsRecord setPicture(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.picture</code>. 商品图片
     */
    public String getPicture() {
        return (String) get(5);
    }

    /**
     * Setter for <code>super.goods.created_at</code>.
     */
    public GoodsRecord setCreatedAt(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>super.goods.updated_at</code>.
     */
    public GoodsRecord setUpdatedAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>super.goods.merchant_id</code>. 供应商id
     */
    public GoodsRecord setMerchantId(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.merchant_id</code>. 供应商id
     */
    public Integer getMerchantId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>super.goods.sale_total</code>. 销售量
     */
    public GoodsRecord setSaleTotal(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.sale_total</code>. 销售量
     */
    public Integer getSaleTotal() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>super.goods.details</code>. 商品详情
     */
    public GoodsRecord setDetails(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.details</code>. 商品详情
     */
    public String getDetails() {
        return (String) get(10);
    }

    /**
     * Setter for <code>super.goods.status</code>. 0-待审核，1-审核成功，2-审核失败
     */
    public GoodsRecord setStatus(Byte value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.status</code>. 0-待审核，1-审核成功，2-审核失败
     */
    public Byte getStatus() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>super.goods.price</code>. 商品价格
     */
    public GoodsRecord setPrice(BigDecimal value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.price</code>. 商品价格
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>super.goods.producer</code>. 生产厂商
     */
    public GoodsRecord setProducer(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.producer</code>. 生产厂商
     */
    public String getProducer() {
        return (String) get(13);
    }

    /**
     * Setter for <code>super.goods.weight</code>. 重量
     */
    public GoodsRecord setWeight(Double value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>super.goods.weight</code>. 重量
     */
    public Double getWeight() {
        return (Double) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, Integer, String, Boolean, String, Timestamp, Timestamp, Integer, Integer, String, Byte, BigDecimal, String, Double> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, Integer, String, Boolean, String, Timestamp, Timestamp, Integer, Integer, String, Byte, BigDecimal, String, Double> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Goods.GOODS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Goods.GOODS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Goods.GOODS.COMMODITY_CLASSIFY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Goods.GOODS.DESCRIBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Goods.GOODS.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Goods.GOODS.PICTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Goods.GOODS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Goods.GOODS.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Goods.GOODS.MERCHANT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Goods.GOODS.SALE_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Goods.GOODS.DETAILS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field12() {
        return Goods.GOODS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field13() {
        return Goods.GOODS.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Goods.GOODS.PRODUCER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field15() {
        return Goods.GOODS.WEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCommodityClassifyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getMerchantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getSaleTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getDetails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component12() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component13() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getProducer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component15() {
        return getWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCommodityClassifyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getMerchantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getSaleTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDetails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value12() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value13() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getProducer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value15() {
        return getWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value3(Integer value) {
        setCommodityClassifyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value4(String value) {
        setDescribe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value5(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value6(String value) {
        setPicture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value7(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value8(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value9(Integer value) {
        setMerchantId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value10(Integer value) {
        setSaleTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value11(String value) {
        setDetails(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value12(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value13(BigDecimal value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value14(String value) {
        setProducer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value15(Double value) {
        setWeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord values(Integer value1, String value2, Integer value3, String value4, Boolean value5, String value6, Timestamp value7, Timestamp value8, Integer value9, Integer value10, String value11, Byte value12, BigDecimal value13, String value14, Double value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GoodsRecord
     */
    public GoodsRecord() {
        super(Goods.GOODS);
    }

    /**
     * Create a detached, initialised GoodsRecord
     */
    public GoodsRecord(Integer id, String name, Integer commodityClassifyId, String describe, Boolean enabled, String picture, Timestamp createdAt, Timestamp updatedAt, Integer merchantId, Integer saleTotal, String details, Byte status, BigDecimal price, String producer, Double weight) {
        super(Goods.GOODS);

        set(0, id);
        set(1, name);
        set(2, commodityClassifyId);
        set(3, describe);
        set(4, enabled);
        set(5, picture);
        set(6, createdAt);
        set(7, updatedAt);
        set(8, merchantId);
        set(9, saleTotal);
        set(10, details);
        set(11, status);
        set(12, price);
        set(13, producer);
        set(14, weight);
    }
}
