/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.database.tables.records;


import cn.hlvan.database.tables.Product;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record8<Integer, String, Timestamp, Timestamp, Timestamp, Integer, Timestamp, Byte> {

    private static final long serialVersionUID = -997146203;

    /**
     * Setter for <code>super.product.id</code>. 商品库存
     */
    public ProductRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>super.product.id</code>. 商品库存
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>super.product.product_code</code>. 产品id
     */
    public ProductRecord setProductCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>super.product.product_code</code>. 产品id
     */
    public String getProductCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>super.product.created_at</code>.
     */
    public ProductRecord setCreatedAt(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>super.product.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>super.product.updated_at</code>.
     */
    public ProductRecord setUpdatedAt(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>super.product.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>super.product.pass_time</code>. 过期时间
     */
    public ProductRecord setPassTime(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>super.product.pass_time</code>. 过期时间
     */
    public Timestamp getPassTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>super.product.commodity_id</code>. 商品id
     */
    public ProductRecord setCommodityId(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>super.product.commodity_id</code>. 商品id
     */
    public Integer getCommodityId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>super.product.product_date</code>. 生产日期
     */
    public ProductRecord setProductDate(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>super.product.product_date</code>. 生产日期
     */
    public Timestamp getProductDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>super.product.status</code>. 0-待出售，1-已售出，2-已过期
     */
    public ProductRecord setStatus(Byte value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>super.product.status</code>. 0-待出售，1-已售出，2-已过期
     */
    public Byte getStatus() {
        return (Byte) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Timestamp, Timestamp, Timestamp, Integer, Timestamp, Byte> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Timestamp, Timestamp, Timestamp, Integer, Timestamp, Byte> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Product.PRODUCT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Product.PRODUCT.PRODUCT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Product.PRODUCT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Product.PRODUCT.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Product.PRODUCT.PASS_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Product.PRODUCT.COMMODITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Product.PRODUCT.PRODUCT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return Product.PRODUCT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProductCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getPassTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getCommodityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getProductDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProductCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getPassTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCommodityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getProductDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value2(String value) {
        setProductCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value3(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value4(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value5(Timestamp value) {
        setPassTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value6(Integer value) {
        setCommodityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value7(Timestamp value) {
        setProductDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value8(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4, Timestamp value5, Integer value6, Timestamp value7, Byte value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Integer id, String productCode, Timestamp createdAt, Timestamp updatedAt, Timestamp passTime, Integer commodityId, Timestamp productDate, Byte status) {
        super(Product.PRODUCT);

        set(0, id);
        set(1, productCode);
        set(2, createdAt);
        set(3, updatedAt);
        set(4, passTime);
        set(5, commodityId);
        set(6, productDate);
        set(7, status);
    }
}
