/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.database.tables.records;


import cn.hlvan.database.tables.System;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemRecord extends UpdatableRecordImpl<SystemRecord> implements Record6<Integer, String, String, Boolean, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1248723699;

    /**
     * Setter for <code>super.system.id</code>. 系统id
     */
    public SystemRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>super.system.id</code>. 系统id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>super.system.code</code>. 系统码
     */
    public SystemRecord setCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>super.system.code</code>. 系统码
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>super.system.name</code>. 系统名称
     */
    public SystemRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>super.system.name</code>. 系统名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>super.system.enabled</code>.
     */
    public SystemRecord setEnabled(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>super.system.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>super.system.created_at</code>.
     */
    public SystemRecord setCreatedAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>super.system.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>super.system.updated_at</code>.
     */
    public SystemRecord setUpdatedAt(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>super.system.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Boolean, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Boolean, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return System.SYSTEM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return System.SYSTEM.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return System.SYSTEM.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return System.SYSTEM.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return System.SYSTEM.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return System.SYSTEM.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SystemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SystemRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SystemRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SystemRecord value4(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SystemRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SystemRecord value6(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SystemRecord values(Integer value1, String value2, String value3, Boolean value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemRecord
     */
    public SystemRecord() {
        super(System.SYSTEM);
    }

    /**
     * Create a detached, initialised SystemRecord
     */
    public SystemRecord(Integer id, String code, String name, Boolean enabled, Timestamp createdAt, Timestamp updatedAt) {
        super(System.SYSTEM);

        set(0, id);
        set(1, code);
        set(2, name);
        set(3, enabled);
        set(4, createdAt);
        set(5, updatedAt);
    }
}
