/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.database.tables.records;


import cn.hlvan.database.tables.User;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record13<Integer, String, String, String, String, Boolean, Byte, String, Timestamp, Timestamp, String, String, String> {

    private static final long serialVersionUID = 1223928297;

    /**
     * Setter for <code>super.user.id</code>. 用户id
     */
    public UserRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>super.user.id</code>. 用户id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>super.user.account</code>.
     */
    public UserRecord setAccount(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>super.user.account</code>.
     */
    public String getAccount() {
        return (String) get(1);
    }

    /**
     * Setter for <code>super.user.name</code>. 用户名称
     */
    public UserRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>super.user.name</code>. 用户名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>super.user.password</code>. 用户密码
     */
    public UserRecord setPassword(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>super.user.password</code>. 用户密码
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>super.user.address</code>. 用户地址
     */
    public UserRecord setAddress(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>super.user.address</code>. 用户地址
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>super.user.enabled</code>.
     */
    public UserRecord setEnabled(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>super.user.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>super.user.type</code>. 用户身份(1-超级管理员，2-部门管理员，3-普通用户)
     */
    public UserRecord setType(Byte value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>super.user.type</code>. 用户身份(1-超级管理员，2-部门管理员，3-普通用户)
     */
    public Byte getType() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>super.user.picture</code>. 用户头像
     */
    public UserRecord setPicture(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>super.user.picture</code>. 用户头像
     */
    public String getPicture() {
        return (String) get(7);
    }

    /**
     * Setter for <code>super.user.created_at</code>.
     */
    public UserRecord setCreatedAt(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>super.user.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>super.user.updated_at</code>.
     */
    public UserRecord setUpdatedAt(Timestamp value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>super.user.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>super.user.business_license</code>. 营业执照
     */
    public UserRecord setBusinessLicense(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>super.user.business_license</code>. 营业执照
     */
    public String getBusinessLicense() {
        return (String) get(10);
    }

    /**
     * Setter for <code>super.user.id_card_photo</code>. 身份证照片
     */
    public UserRecord setIdCardPhoto(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>super.user.id_card_photo</code>. 身份证照片
     */
    public String getIdCardPhoto() {
        return (String) get(11);
    }

    /**
     * Setter for <code>super.user.store_picture</code>. 门店图片
     */
    public UserRecord setStorePicture(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>super.user.store_picture</code>. 门店图片
     */
    public String getStorePicture() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, Boolean, Byte, String, Timestamp, Timestamp, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, Boolean, Byte, String, Timestamp, Timestamp, String, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return User.USER.ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return User.USER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return User.USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return User.USER.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return User.USER.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return User.USER.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return User.USER.PICTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return User.USER.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return User.USER.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return User.USER.BUSINESS_LICENSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return User.USER.ID_CARD_PHOTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return User.USER.STORE_PICTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getBusinessLicense();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getIdCardPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getStorePicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getBusinessLicense();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getIdCardPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getStorePicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value2(String value) {
        setAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value5(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value6(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value7(Byte value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value8(String value) {
        setPicture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value9(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value10(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value11(String value) {
        setBusinessLicense(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value12(String value) {
        setIdCardPhoto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value13(String value) {
        setStorePicture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord values(Integer value1, String value2, String value3, String value4, String value5, Boolean value6, Byte value7, String value8, Timestamp value9, Timestamp value10, String value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String account, String name, String password, String address, Boolean enabled, Byte type, String picture, Timestamp createdAt, Timestamp updatedAt, String businessLicense, String idCardPhoto, String storePicture) {
        super(User.USER);

        set(0, id);
        set(1, account);
        set(2, name);
        set(3, password);
        set(4, address);
        set(5, enabled);
        set(6, type);
        set(7, picture);
        set(8, createdAt);
        set(9, updatedAt);
        set(10, businessLicense);
        set(11, idCardPhoto);
        set(12, storePicture);
    }
}
